"""empty message

Revision ID: 2e5f35e416bc
Revises: None
Create Date: 2016-10-31 14:26:46.268346

"""

# revision identifiers, used by Alembic.
revision = '2e5f35e416bc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    ### end Alembic commands ###
